<a href="https://colab.research.google.com/github/rmonterof/Python/blob/main/1_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

https://numpy.org/doc/stable/

https://numpy.org/doc/stable/user/absolute_beginners.html

In [ ]:
# !pip install numpy

In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

## 1. Crear arrays

### np.array

In [ ]:
numbers = [1, 2, 3, 4]
numbers

[1, 2, 3, 4]

In [ ]:
arr = np.array([1, 4, 2, 5, 3])
arr

array([1, 4, 2, 5, 3])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
numbers_tuple = (1,2,3)
numbers_list = list(numbers_tuple)
numbers_list

[1, 2, 3]

In [ ]:
type(numbers)

list

In [ ]:
np.array((1,2))

array([1, 2])

In [ ]:
np.array([1, 2, 3, 4], dtype='float16')

array([1., 2., 3., 4.], dtype=float16)

### np.zeros

In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### np.ones

In [ ]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### np.full

In [ ]:
np.full((3, 5), 15)

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

### np.arange

In [ ]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
np.arange(20)  # stop

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(5, 20)  # start, stop

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(5, 20, 3)  # start, stop, step

array([ 5,  8, 11, 14, 17])

In [ ]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### np.linspace

Devuelve números espaciados uniformemente en un intervalo específico.

In [ ]:
np.linspace(0, 1, 12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

### np.random

https://numpy.org/doc/stable/reference/random/index.html

In [ ]:
np.random.random((3, 3))  # valores entre 0 y 1

array([[0.69962205, 0.3277204 , 0.75677864],
       [0.63606106, 0.24002027, 0.16053882],
       [0.79639147, 0.9591666 , 0.45813883]])

In [ ]:
np.random.randint(0, 10, (3, 3))  # valores entre 0 y 10 excluido

array([[2, 5, 6],
       [4, 2, 2],
       [1, 0, 9]])

In [ ]:
np.random.normal(0, 1, (3, 3))

array([[ 0.49374178, -0.11610394, -2.03068447],
       [ 2.06449286, -0.11054066,  1.02017271],
       [-0.69204985,  1.53637705,  0.28634369]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr1 = np.empty(6)
arr1.ndim

1

## 2. Atributos de arrays

In [ ]:
np.random.seed(0) # seed for reproducibility

In [ ]:
x1 = np.random.randint(10, size=6) # One-dimensional array
x1

array([8, 8, 1, 6, 7, 7])

In [ ]:
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x2

array([[0, 4, 7, 3],
       [2, 7, 2, 0],
       [0, 4, 5, 5]])

In [ ]:
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array
x3

array([[[4, 5, 0, 3, 1],
        [4, 4, 4, 0, 0],
        [8, 4, 6, 9, 3],
        [3, 2, 1, 2, 1]],

       [[3, 4, 1, 1, 0],
        [7, 8, 4, 3, 5],
        [6, 3, 2, 9, 8],
        [1, 4, 0, 8, 3]],

       [[9, 5, 5, 1, 7],
        [8, 6, 4, 7, 3],
        [5, 3, 6, 4, 7],
        [3, 0, 5, 9, 3]]])

In [ ]:
x2

array([[3, 3, 9, 2],
       [5, 2, 3, 5],
       [7, 2, 7, 1]])

In [ ]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)
print("dtype:", x2.dtype)
print("itemsize:", x2.itemsize, "bytes")
print("nbytes:", x2.nbytes, "bytes")

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12
dtype: int64
itemsize: 8 bytes
nbytes: 96 bytes


In [ ]:
x3

array([[[4, 5, 0, 3, 1],
        [4, 4, 4, 0, 0],
        [8, 4, 6, 9, 3],
        [3, 2, 1, 2, 1]],

       [[3, 4, 1, 1, 0],
        [7, 8, 4, 3, 5],
        [6, 3, 2, 9, 8],
        [1, 4, 0, 8, 3]],

       [[9, 5, 5, 1, 7],
        [8, 6, 4, 7, 3],
        [5, 3, 6, 4, 7],
        [3, 0, 5, 9, 3]]])

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


\\[texto del enlace](https://)## 3. Acceder a los elementos: indexación

In [ ]:
x1  # array de 1 dimensión

array([8, 8, 1, 6, 7, 7])

In [ ]:
print(x1[0])
print(x1[1])
print(x1[2])

8
8
1


In [ ]:
print(x1[-1])
print(x1[-2])
print(x1[-3])

7
7
6


In [ ]:
x2  # array de 2 dimensiones

array([[0, 4, 7, 3],
       [2, 7, 2, 0],
       [0, 4, 5, 5]])

In [ ]:
print(x2[0,0])
print(x2[0,1])
print(x2[0,2])
print(x2[0,3])
print(x2[1,0])
print(x2[1,1])
print(x2[1,2])
print(x2[2,3])

0
4
7
3
2
7
2
5


In [ ]:
x3[0,0,0]

np.int64(4)

In [ ]:
x2[0][0]

np.int64(0)

In [ ]:
print(x2[0,-1])

3


In [ ]:
x2.dtype

dtype('int64')

In [ ]:
print("Valor original:", x2[0,0])
x2[0,0] = 8.9
print("Valor modificado:", x2[0,0])

Valor original: 8
Valor modificado: 8


## 4. Acceder a subarrays: slicing

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[::2] # start, stop, step

array([0, 2, 4, 6, 8])

In [ ]:
print(x[:5])  # start, stop, step
print(x[5:])
print(x[3:7])

[0 1 2 3 4]
[5 6 7 8 9]
[3 4 5 6]


In [ ]:
print(x[::2])
print(x[1::2])
print(x[::-1])
print(x[::1])

[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
x2

array([[8, 4, 7, 3],
       [2, 7, 2, 0],
       [0, 4, 5, 5]])

In [ ]:
x2[:2, 1:3]

array([[4, 7],
       [7, 2]])

In [ ]:
x2[:2, ::2]

array([[8, 7],
       [2, 2]])

In [ ]:
print(x2[:, 0])
print(x2[0, :])

[8 2 0]
[8 4 7 3]


## 5. Copy vs. view

Las operaciones slicing devuelven vistas no copias.
Significa que si se cambian datos en el array original también
se cambian en la vista.

In [ ]:
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x2

array([[3, 3, 9, 2],
       [5, 2, 3, 5],
       [7, 2, 7, 1]])

In [ ]:
x2_sub = x2[:2, :2]  # técnica slicing
x2_sub

array([[3, 3],
       [5, 0]])

In [ ]:
x2_sub[0, 0] = 99  # Al modificar en uno se modifica en los dos

In [ ]:
print(x2)
print('\n')
print(x2_sub)

[[99  3  7  8]
 [ 5  0  8  5]
 [ 4  7  4  1]]


[[99  3]
 [ 5  0]]


Se utiliza el método copy() para poder generar una nueva copia de manera que los cambios no afecten al array original

In [ ]:
x2_sub_copy = x2[:2, :2].copy()  # método copy() para crear una copia independiente

In [ ]:
x2_sub_copy[0, 0] = 50

In [ ]:
print(x2)
print('\n')
print(x2_sub_copy)

[[99  9  3  0]
 [ 5  0  1  2]
 [ 4  2  0  3]]


[[50  9]
 [ 5  0]]


## 6. Redimensionar un array (reshape)

### reshape

In [ ]:
x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [ ]:
x.ndim

1

In [ ]:
x.shape

(9,)

In [ ]:
type(x.shape)

tuple

In [ ]:
x_2d = x.reshape((3, 3))
print(x_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x_2d.ndim

2

In [ ]:
print(x.reshape((1, 9)))  # 2 dimensiones: 1 fila y 9 columnas

[[1 2 3 4 5 6 7 8 9]]


In [ ]:
x.reshape((1, 9)).ndim

2

### np.newaxis

In [ ]:
print(x); print(x.ndim); print(x.shape)

[1 2 3 4 5 6 7 8 9]
1
(9,)


In [ ]:
y = x[np.newaxis, :]; print(y); print(y.ndim); print(y.shape)

[[1 2 3 4 5 6 7 8 9]]
2
(1, 9)


In [ ]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [ ]:
arr.shape

(4,)

In [ ]:
row_vec = arr[np.newaxis]
row_vec

array([[0, 1, 2, 3]])

In [ ]:
row_vec.shape

(1, 4)

In [ ]:
col_vec = arr[:, np.newaxis]
col_vec

array([[0],
       [1],
       [2],
       [3]])

In [ ]:
col_vec.shape

(4, 1)

In [ ]:
arr[np.newaxis, np.newaxis, :]

array([[[0, 1, 2, 3]]])

In [ ]:
arr[:, np.newaxis, np.newaxis]

array([[[0]],

       [[1]],

       [[2]],

       [[3]]])

### ravel

In [ ]:
x = np.array([1, 2, 3, 4, 5])
print(x); print(np.ravel(x))

[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
print(np.ravel(x))
print(np.ravel(x).ndim)

[1 2 3 4 5 6]
1


## 7. Concatenar arrays

### concatenate

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = [99, 99, 99]

print(x); print(y); print(z); print('\n')

print(np.concatenate([x, y]))
print(np.concatenate([x, y, z]))
print(x)

[1 2 3]
[4 5 6]
[99, 99, 99]


[1 2 3 4 5 6]
[ 1  2  3  4  5  6 99 99 99]
[1 2 3]


In [ ]:
grid = np.array([ [1, 2, 3], [4, 5, 6] ])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print("shape", grid.shape); print("dimensiones", grid.ndim)

shape (2, 3)
dimensiones 2


In [ ]:
y = np.concatenate([grid, grid])
print(y); print(y.ndim); print(y.shape)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
2
(4, 3)


In [ ]:
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### vstack

In [ ]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [ ]:
grid = np.array([ [9, 8, 7], [6, 5, 4] ])
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [ ]:
# Da error porque x tiene 1 dimensión y grid tiene 2 dimensiones
# np.concatenate([x, grid], axis=0)

In [ ]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

### hstack

In [ ]:
# Da error porque x tiene 1 dimensión y grid tiene 2 dimensiones
# np.hstack([x, grid])

In [ ]:
y = np.array([4, 5, 6])
np.hstack([x, y])

array([1, 2, 3, 4, 5, 6])

In [ ]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [ ]:
y = np.array([[99], [99]])
y

array([[99],
       [99]])

In [ ]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [ ]:
y = np.array([4, 5])
y

array([4, 5])

In [ ]:
y = y.reshape(2, 1)
y

array([[4],
       [5]])

In [ ]:
np.hstack([grid, y])

array([[9, 8, 7, 4],
       [6, 5, 4, 5]])

## 8.  Separar arrays (split)

### split()

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [ ]:
x1, x2, x3 = np.split(x, [3, 5])
print(x1)
print(x2)
print(x3)

[1 2 3]
[99 99]
[3 2 1]


### vsplit()

In [ ]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper, lower = np.vsplit(grid, [1])
print(upper)
print('\n')
print(lower)

[[0 1 2 3]]


[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print('\n')
print(lower)

[[0 1 2 3]
 [4 5 6 7]]


[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
upper, lower = np.vsplit(grid, [3])
print(upper)
print('\n')
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]]


### hsplit()

In [ ]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print('\n')
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
left, right = np.hsplit(grid, [3])
print(left)
print('\n')
print(right)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


[[ 3]
 [ 7]
 [11]
 [15]]


## 9. Operaciones sobre arrays

* https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs
* https://numpy.org/doc/stable/reference/routines.html
* https://numpy.org/doc/stable/reference/routines.math.html
* https://numpy.org/doc/stable/reference/routines.statistics.html


### aritméticas

In [ ]:
# listas de python
# numbers = [1,2,3]
# numbers + 2  # TypeError: can only concatenate list (not "int") to list

In [ ]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [ ]:
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("x ** 2 =", x ** 2)
print("-x = ", -x)
print("x % 2 = ", x % 2)

x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
x ** 2 = [0 1 4 9]
-x =  [ 0 -1 -2 -3]
x % 2 =  [0 1 0 1]


In [ ]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [ ]:
print(np.arange(5))
print(np.arange(1,6))

[0 1 2 3 4]
[1 2 3 4 5]


In [ ]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [ ]:
np.arange(5) // np.arange(1, 6)  # División suelo elimina la parte decimal

array([0, 0, 0, 0, 0])

In [ ]:
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [ ]:
x ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

### np.absolute

In [ ]:
x = np.array([-2, -1, 0, 1, 2])
x

array([-2, -1,  0,  1,  2])

In [ ]:
np.absolute(x)  # ``np.abs`` is a shorthand for this function.

array([2, 1, 0, 1, 2])

In [ ]:
np.abs(x)

array([2, 1, 0, 1, 2])

### trigonométricas

In [ ]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [ ]:
print("theta      =", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tag(theta) =", np.tan(theta))

theta      = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tag(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
x = [-1, 0, 1]

In [ ]:
print("arcsin(x) =", np.arcsin(x))
print("arccos(x) =", np.arccos(x))
print("arctan(x) =", np.arctan(x))

arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


### exponenciales y logarítmicas

In [ ]:
x = [1, 2, 3]
x

[1, 2, 3]

In [ ]:
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("4^x   =", np.power(4, x))

e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
4^x   = [ 4 16 64]


In [ ]:
x = [1, 2, 4, 10]
x

[1, 2, 4, 10]

In [ ]:
print("ln(x)   =", np.log(x))
print("ln2(x)   =", np.log2(x))
print("ln10(x)   =", np.log10(x))

ln(x)   = [0.         0.69314718 1.38629436 2.30258509]
ln2(x)   = [0.         1.         2.         3.32192809]
ln10(x)   = [0.         0.30103    0.60205999 1.        ]


In [ ]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [ ]:
y = np.empty(5)
np.multiply(x, 10, out=y)

array([ 0., 10., 20., 30., 40.])

In [ ]:
y

array([ 0., 10., 20., 30., 40.])

### reduce

In [ ]:
x = np.arange(1, 6)
x

array([1, 2, 3, 4, 5])

In [ ]:
x + 5

array([ 6,  7,  8,  9, 10])

In [ ]:
np.add(x, 5)

array([ 6,  7,  8,  9, 10])

In [ ]:
cont = 0
for i in x:
    cont += i; print(cont)

1
3
6
10
15


In [ ]:
np.add.reduce(x)  # lo mismo que lo anterior pero más óptimo

np.int64(15)

In [ ]:
np.multiply.reduce(x)

np.int64(120)

### accumulate

In [ ]:
x

array([1, 2, 3, 4, 5])

In [ ]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [ ]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

### outer()

In [ ]:
print(x)

[1 2 3 4 5]


In [ ]:
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

### min(), max(), sum()

In [ ]:
big_array = np.random.rand(10000)

In [ ]:
# descomentar para evaluar, puede tardar un poco en ejecutar
# %timeit sum(big_array)
# %timeit np.sum(big_array)

In [ ]:
np.min(big_array)

np.float64(2.0027530115096503e-05)

In [ ]:
np.max(big_array)

np.float64(0.9999709462497284)

In [ ]:
matrix = np.random.random((3, 4))
matrix

array([[0.27720631, 0.92986366, 0.87019482, 0.42864927],
       [0.79020752, 0.53822602, 0.10914046, 0.06830124],
       [0.2574038 , 0.29826429, 0.47546038, 0.4323291 ]])

In [ ]:
matrix.sum()

np.float64(5.475246863457526)

In [ ]:
matrix.min()

np.float64(0.06830124015122596)

In [ ]:
matrix.min(axis=0)

array([0.2574038 , 0.29826429, 0.10914046, 0.06830124])

In [ ]:
matrix.min(axis=1)

array([0.27720631, 0.06830124, 0.2574038 ])

### Ejemplo

In [ ]:
# !pip install pandas

In [ ]:
import pandas as pd
df = pd.read_csv('../data/president_heights.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/president_heights.csv'

In [ ]:
# obtener un array de numpy a partir del dataframe de pandas
print(type(df['height(cm)']))
heights = np.array(df['height(cm)'])
print(type(heights))
heights = df['height(cm)'].values
print(type(heights))

In [ ]:
heights

In [ ]:
print("Altura media =   ", heights.mean())
print("Desviación estándar =   ", heights.std())
print("Altura mínima =   ", heights.min())
print("Altura máxima =   ", heights.max())
print("Percentil 25 =   ", np.percentile(heights, 25))
print("Mediana =   ", np.median(heights))
print("Percentil 75 =   ", np.percentile(heights, 75))

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(heights)
plt.title('Height Distribution of US Presidents')
plt.xlabel('height (cm)')
plt.ylabel('number');

## 10. Broadcasting

Reglas para aplicar ufuncs binarias (suma, resta, multiplicación, etc) a arrays de diferentes tamaños

In [ ]:
# Arrays del mismo tamaño
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

In [ ]:
a = np.array([0, 1, 2])

In [ ]:
c = np.ones((3, 3))
c

In [ ]:
a + c  # Arrays de diferente tamaño

In [ ]:
a + 5

In [ ]:
print(np.arange(3))
print(np.arange(3) + 5)

### Ejemplo 1

In [ ]:
a = np.ones((2, 3))
print(a)
print(a.shape) # (2, 3)

In [ ]:
b = np.arange(3)
print(b)
print(b.shape) # (1, 3)

In [ ]:
a + b

### Ejemplo 2

In [ ]:
print(np.arange(3).reshape(3,1))
print('\n')
print(np.arange(3))
print('\n')
print(np.arange(3).reshape(3,1) + np.arange(3))

In [ ]:
a = np.arange(3).reshape((3, 1))
print(a)
print(a.shape)  # (3,1)

[[0]
 [1]
 [2]]
(3, 1)


In [ ]:
b = np.arange(3)
print(b)
print(b.shape) # (1, 3)

[0 1 2]
(3,)


In [ ]:
c = a + b
print(c)
print(c.shape)

[[0 1 2]
 [1 2 3]
 [2 3 4]]
(3, 3)


### Ejemplo 3

In [ ]:
a = np.ones((3, 2))
print(a)
print(a.shape) # (3,2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
(3, 2)


In [ ]:
b = np.arange(3)
print(b)
print(b.shape) # (1, 3)

[0 1 2]
(3,)


In [ ]:
# Proceso:
# (3,2) + (1,3)
# (3,2) + (3,3) --> LAs dimensiones no coinciden

# a + b  # Produce error dado que (3,2) + (3,3) son tamaños diferentes

## 11. Comparación y filtros, lógica booleana

In [ ]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [ ]:
x < 3

array([ True,  True, False, False, False])

In [ ]:
x > 3

array([False, False, False,  True,  True])

In [ ]:
x <= 3

array([ True,  True,  True, False, False])

In [ ]:
x >= 3

array([False, False,  True,  True,  True])

In [ ]:
x != 3

array([ True,  True, False,  True,  True])

In [ ]:
x == 3

array([False, False,  True, False, False])

In [ ]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

### Arrays booleanos

In [ ]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [ ]:
np.count_nonzero(x < 6)

8

In [ ]:
np.sum(x < 6)  # Contar el número de elementos menores que 6 en total

np.int64(8)

In [ ]:
np.sum(x < 6, axis=1) # Contar el número de elementos menores que 6 en cada fila

array([4, 2, 2])

### Ejemplo de lógica booleana sobre array de precios

In [ ]:
# cargar dataset con pandas
df = pd.read_csv('../data/tips.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: '../data/tips.csv'

In [ ]:
# guarda en la variable total_bill un array numpy con los valores de la columna total_bill del csv
total_bill = df['total_bill'].values

print(type(df))
print(type(df['total_bill']))
print(type(total_bill))
print(total_bill.shape)

In [ ]:
total_bill[:50]  # Imprime los 50 primeros pagos

NameError: name 'total_bill' is not defined

In [ ]:
print("Número total de pagos =          ", total_bill.size)
print("Suma total de pagos =          ", np.sum(total_bill), "$")
print('\n')
# Lógica booleana para filtrar datos:
print("Número total de pagos de 21.01 $ = ", np.sum(total_bill == 21.01))
print("Número total de pagos menores de 10 $ = ", np.sum(total_bill < 10))
print("Número total de pagos entre 10 y 15 $ = ", np.sum((total_bill >= 10) & (total_bill < 15)))
print("Número total de pagos mayores de 15 $ = ", np.sum(total_bill >= 15))

NameError: name 'total_bill' is not defined

In [ ]:
total_bill < 10

NameError: name 'total_bill' is not defined

In [ ]:
total_bill[total_bill < 10]

NameError: name 'total_bill' is not defined

In [ ]:
total_bill[~(total_bill < 10)] # negación de la condición, devuelve todos aquellos que incumplan la condición

NameError: name 'total_bill' is not defined

## 12. Fancy indexing

Consiste en acceder a múltiples elementos a la vez

In [ ]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [ ]:
print(x[0])
print(x[6])
print(x[2])

51
82
14


In [ ]:
x[[0, 6, 2]]
# x[0, 6, 2]  # No confundir con lo anterior, en este caso trata de acceder a 3 dimensiones lo que da error.

array([51, 82, 14])

In [ ]:
[x[3], x[7], x[2]]

[np.int64(71), np.int64(86), np.int64(14)]

In [ ]:
indices = [3, 7, 4]
x[indices]

array([71, 86, 60])

In [ ]:
indices = np.array([[3, 7],
                    [4, 5]])
x[indices]

array([[71, 86],
       [60, 20]])

In [ ]:
a = np.arange(12).reshape((3, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
a[row, col]

array([ 2,  5, 11])

In [ ]:
# combinar slicing con fancy indexing:
a[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

## 13. Ordenar arrays: sort()

In [ ]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [ ]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)  # devuelve los índices en lugar de los valores
print(i)
print(type(i))
print(x[i])

[1 0 3 2 4]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [ ]:
rand = np.random.RandomState(42)
a = rand.randint(0, 10, (4, 6))
print(a)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [ ]:
np.sort(a)  # Por defecto ordena las filas

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [ ]:
np.sort(a, axis=0)  # ordena las columnas

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [ ]:
np.sort(a, axis=1)  # ordena las filas

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## 14. Arrays estructurados

Arrays con datos heterogéneos

In [ ]:
# A priori se pueden crear arrays de diferentes tipos:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]
# El problema es manejarlos en sincronía ya que son arrays diferentes, mejor crear en un mismo array

In [ ]:
# U10 significa string Unicode de longitud 10
# i4 significa integer de 4 bytes
# f8 significa float de 8 bytes
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),'formats':('U10', 'i4', 'f8')})
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [ ]:
print("size:", data.size)
print("ndim", data.ndim)
print("shape", data.shape)

size: 4
ndim 1
shape (4,)


In [ ]:
# asignar los datos:
data['name'] = name  # string
data['age'] = age  # int
data['weight'] = weight  # float
print(data)

NameError: name 'name' is not defined

In [ ]:
# obtener la primera fila
data[0]

np.void(('Alice', 25, 55.0), dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [ ]:
print(type(data[0]))

NameError: name 'data' is not defined

In [ ]:
# Obtener el nombre de la primera fila
data[0]['name']

np.str_('Alice')

In [ ]:
data[1]['age']

np.int32(45)

In [ ]:
# Obtener el nombre de todas las filas:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [ ]:
data['age']

array([25, 45, 37, 19], dtype=int32)

In [ ]:
# Obtener solo nombres cuyas edades sean menor de 30
data[data['age'] < 30]['name']

NameError: name 'data' is not defined